//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAppointment
    {
        public int AID { get; set; }
        public Nullable<int> SsID { get; set; }
        public Nullable<int> ASID { get; set; }
        public string CPhone { get; set; }
        public Nullable<System.DateTime> BookedDay { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> ACapital { get; set; }
    
        public virtual tbCustomer tbCustomer { get; set; }
        public virtual tbAppointmentStatu tbAppointmentStatu { get; set; }
        public virtual tbSession tbSession { get; set; }
    }
}
