//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPromotion
    {
        public int PID { get; set; }
        public Nullable<int> SID { get; set; }
        public string PImage { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> StartDay { get; set; }
        public Nullable<System.DateTime> EndDay { get; set; }
        public string PDescription { get; set; }
    
        public virtual tbStore tbStore { get; set; }
    }
}
