//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSession()
        {
            this.tbAppointments = new HashSet<tbAppointment>();
        }
    
        public int SsID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> Capital { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<System.DateTime> DayCreate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAppointment> tbAppointments { get; set; }
        public virtual tbStore tbStore { get; set; }
    }
}
