//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbStore()
        {
            this.tbPromotions = new HashSet<tbPromotion>();
            this.tbReviews = new HashSet<tbReview>();
            this.tbSessions = new HashSet<tbSession>();
        }
    
        public int SID { get; set; }
        public string SPhone { get; set; }
        public string SName { get; set; }
        public string SAddress { get; set; }
        public string PriceAvg { get; set; }
        public string SDescription { get; set; }
        public string Latitude { get; set; }
        public string Longtitude { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public Nullable<int> SCapital { get; set; }
        public string SImage { get; set; }
        public string CPhone { get; set; }
        public Nullable<double> NumberStar { get; set; }
    
        public virtual tbCustomer tbCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPromotion> tbPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReview> tbReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSession> tbSessions { get; set; }
    }
}
