//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ItbAppointmentService : SkyWeb.DatVM.Data.IBaseService<tbAppointment>
    {
    }
    
    public partial class tbAppointmentService : SkyWeb.DatVM.Data.BaseService<tbAppointment>, ItbAppointmentService
    {
        public tbAppointmentService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ItbAppointmentRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
