//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ItbAppointmentStatuService : SkyWeb.DatVM.Data.IBaseService<tbAppointmentStatu>
    {
    }
    
    public partial class tbAppointmentStatuService : SkyWeb.DatVM.Data.BaseService<tbAppointmentStatu>, ItbAppointmentStatuService
    {
        public tbAppointmentStatuService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ItbAppointmentStatuRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
