//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ItbPromotionService : SkyWeb.DatVM.Data.IBaseService<tbPromotion>
    {
    }
    
    public partial class tbPromotionService : SkyWeb.DatVM.Data.BaseService<tbPromotion>, ItbPromotionService
    {
        public tbPromotionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ItbPromotionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
