//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ItbStoreService : SkyWeb.DatVM.Data.IBaseService<tbStore>
    {
    }
    
    public partial class tbStoreService : SkyWeb.DatVM.Data.BaseService<tbStore>, ItbStoreService
    {
        public tbStoreService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ItbStoreRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
