//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCustomerViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.tbCustomer>
    {
    	
    			public virtual string CPhone { get; set; }
    			public virtual string CPassword { get; set; }
    			public virtual string CName { get; set; }
    			public virtual string CEmail { get; set; }
    			public virtual Nullable<int> RoleID { get; set; }
    	
    	public tbCustomerViewModel() : base() { }
    	public tbCustomerViewModel(HmsService.Models.Entities.tbCustomer entity) : base(entity) { }
    
    }
}
