//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStoreViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.tbStore>
    {
    	
    			public virtual int SID { get; set; }
    			public virtual string SPhone { get; set; }
    			public virtual string SName { get; set; }
    			public virtual string SAddress { get; set; }
    			public virtual string PriceAvg { get; set; }
    			public virtual string SDescription { get; set; }
    			public virtual string Latitude { get; set; }
    			public virtual string Longtitude { get; set; }
    			public virtual Nullable<System.TimeSpan> StartTime { get; set; }
    			public virtual Nullable<System.TimeSpan> CloseTime { get; set; }
    			public virtual Nullable<int> SCapital { get; set; }
    			public virtual string SImage { get; set; }
    			public virtual string CPhone { get; set; }
    			public virtual Nullable<double> NumberStar { get; set; }
    	
    	public tbStoreViewModel() : base() { }
    	public tbStoreViewModel(HmsService.Models.Entities.tbStore entity) : base(entity) { }
    
    }
}
